const allStocksMock = [
  {
    symbol: 'SPY',
    name: 'SPDR S&P 500 ETF Trust',
    price: 435.18,
    exchange: 'New York Stock Exchange Arca',
    exchangeShortName: 'AMEX',
    type: 'etf',
    tradable: true,
  },
  {
    symbol: 'CMCSA',
    name: 'Comcast Corporation',
    price: 52.69,
    exchange: 'Nasdaq Global Select',
    exchangeShortName: 'NASDAQ',
    type: 'stock',
    tradable: true,
  },
  {
    symbol: 'KMI',
    name: 'Kinder Morgan, Inc.',
    price: 17.97,
    exchange: 'New York Stock Exchange',
    exchangeShortName: 'NYSE',
    type: 'stock',
    tradable: true,
  },
  {
    symbol: 'INTC',
    name: 'Intel Corporation',
    price: 52.26,
    exchange: 'Nasdaq Global Select',
    exchangeShortName: 'NASDAQ',
    type: 'stock',
    tradable: true,
  },
  {
    symbol: 'MU',
    name: 'Micron Technology, Inc.',
    price: 66.38,
    exchange: 'Nasdaq Global Select',
    exchangeShortName: 'NASDAQ',
    type: 'stock',
    tradable: true,
  },
  {
    symbol: 'GDX',
    name: 'VanEck Vectors Gold Miners ETF',
    price: 32.15,
    exchange: 'New York Stock Exchange Arca',
    exchangeShortName: 'AMEX',
    type: 'etf',
    tradable: true,
  },
  {
    symbol: 'GE',
    name: 'General Electric Company',
    price: 102.36,
    exchange: 'New York Stock Exchange',
    exchangeShortName: 'NYSE',
    type: 'stock',
    tradable: true,
  },
  {
    symbol: 'BAC',
    name: 'Bank of America Corporation',
    price: 43.14,
    exchange: 'New York Stock Exchange',
    exchangeShortName: 'NYSE',
    type: 'stock',
    tradable: true,
  },
  {
    symbol: 'EEM',
    name: 'iShares MSCI Emerging Markets ETF',
    price: 51.16,
    exchange: 'New York Stock Exchange Arca',
    exchangeShortName: 'AMEX',
    type: 'etf',
    tradable: true,
  },
  {
    symbol: 'XLF',
    name: 'Financial Select Sector SPDR Fund',
    price: 38.29,
    exchange: 'New York Stock Exchange Arca',
    exchangeShortName: 'AMEX',
    type: 'etf',
    tradable: true,
  },
  {
    symbol: 'AAPL',
    name: 'Apple Inc.',
    price: 140.91,
    exchange: 'Nasdaq Global Select',
    exchangeShortName: 'NASDAQ',
    type: 'stock',
    tradable: true,
  },
];

export default allStocksMock;
